store/product/urls.py
from django.urls import path
from . import views
app_name = "product" # set tên app để phân biệt đường dẫn đến các app khác
urlpatterns = [
    path('', views.Index.as_view(),name="home"),# đường dẫn đến trang chủ
    path("product/<int:product_id>",views.View_product.as_view(),name="view_product"),# đường dẫn đến sản phẩm
    # khi click vào đường dẫn này thì django sẽ truyền vào product_id id của sản phẩm đang chứa đường dẫn
    path("type/<int:type_id>",views.view_type,name="view_type"), # đường dẫn đến loại sản phẩm
    # khi click vào đường dẫn này thì django sẽ truyền vào type_id id của loại hàng đang chứa đường dẫn
    path("search/",views.Search.as_view(),name="search") # đường dẫn đến trang tìm kiếm
]

store/store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
# thêm các thư viện cài đặt để thêm đường dẫn cho ảnh

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("product.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

store/product/models.py
from django.db import models
from django.db.models.aggregates import Count
# Create your models here.


class Product_type(models.Model):
    """lớp biểu diễn loại sản phẩm"""
    name = models.CharField(default="", max_length=256)  # tên loại sản phẩm
    description = models.TextField(default="")  # mô tả loại sản phẩm
    def __str__(self):
        return self.name # khi hiển thị class sẽ hiển thị ra tên 


class Product(models.Model):
    """lớp biểu diễn sản phẩm"""
    name = models.CharField( default="", max_length=1000)  # tên sản phẩm để mặc định là rỗng
    # mô tả sản phẩm dùng trường Text để biểu diễn
    description = models.TextField(default="")
    # chi tiết về sản phẩm
    detail = models.TextField(default="",max_length=10000)
    # biểu diễn sản phẩm có được đưa lên trình chiếu hay không
    active = models.BooleanField(default=False)
    value = models.IntegerField(default=0)  # giá tiền của sản phẩm
    # kết nối đến bảng loại sản phẩm và set sự kiện xóa
    product_type = models.ForeignKey(Product_type, on_delete=models.CASCADE) # liên kết đến bảng loại sản phẩm
    img_avata = models.ImageField(null=True)
    def __str__(self):
        return self.name # khi hiển thị class sẽ hiển thị ra tên
#     lưu ý phải khai báo loại sản phẩm trước sản phẩm
class Picture(models.Model):
    """ lớp biểu diễn ảnh của sản phẩm"""
    product = models.ForeignKey(Product, on_delete=models.CASCADE) # liên kết đến bảng sản phẩm
    picture = models.ImageField(null=True) # ảnh của sản phẩm được biểu diễn dưới trường ảnh
    def __str__(self):
        return self.picture.url # khi hiển thị class sẽ hiển thị ra đường dẫn
class Order(models.Model):
    """ lớp biểu diễn sự đặt hàng, đơn hàng """
    name_user = models.CharField(max_length=256,default="") # tên người đặt
    value = models.IntegerField(default=1) # tổng số tiền cần thanh toán
    count = models.IntegerField(default=1) # số lượng sản phẩm
    address = models.CharField(max_length=256) # địa chỉ người đặt
    phone_number = models.CharField(max_length=11) # số điện thoại người đặt hàng
    name_product = models.CharField(default="",max_length=1000) # tên sản phẩm 
    shipped = models.BooleanField(default=False) # trạng thái đã ship hay chưa
    def __str__(self):
        return  self.name_user + " / " + self.name_product +" / " + self.phone_number 

store/product/forms.py
from django import forms
from django.forms import widgets
from .models import Order
# đây là file chứa các form
class OrderForm(forms.ModelForm):
    """ class biểu diễn form đặt hàng"""
    class Meta:
        model = Order # gán đối tượng cho form
        fields = ("name_user","address","phone_number","count") # tupple các trường được biểu diễn ra
        # chỉnh dao diện cho các forms
        widgets = {"name_user": forms.TextInput(attrs={"class":"form-control form-control-sm"}),
                    "address": forms.TextInput(attrs={"class":"form-control form-control-sm"}),
                    "phone_number": forms.TextInput(attrs={"class":"form-control form-control-sm"}),
                    "count": forms.NumberInput(attrs={"class":"form-control form-control-sm"})
                    }

store/product/views.py
from django import views
from django.db import models
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse 
from .forms import OrderForm
from .models import Order, Product,Product_type
# Create your views here.
class Index(View):
    """ class hiển thị trang chủ """
    def get(self,request):
        """hàm hiển thị""" 
        pros = Product.objects.all() # tạo danh sách chứa toàn bộ sản phẩm
        sliders = [] # tạo 1 danh sách để chiếu trên slider
        prosduct_types = Product_type.objects.all() # tạo danh sách loại sản phẩm
        for i in pros: 
            if i.active: sliders.append(i) # lặp trong toàn bộ sản phẩm nếu được chiếu trên slider thì thêm vào
        first = sliders.pop() # lấy sản phẩm được chiếu trên slider đầu tiên
        # trả về trang template thị sản phẩm và truyền vào đó dic chứa sản phẩm,sliders,loại sản phẩm
        return render(request,"product/index.html",{"pros":pros,"sliders": sliders,"first":first,"product_types":prosduct_types})
class View_product(View):
    """class chứa trang hiển thị sản phẩm"""
    def get(self,request,product_id):
        p = Product.objects.get(pk=product_id)  # lấy sản phẩm theo key truyền vào từ đường dẫn
        f = OrderForm() # tạo 1 form đặt hàng để cho khách hàng có thể đặt hàng
        return render(request,"product/view_product.html",{"pro":p,"f":f})
        # trả về template hiển thị sản phầm và truyền vào đó dic chứa sản phẩm
        #  key của đối tượng sẽ biểu diễn cho đối tượng đó trong template 
    def post(self,request,product_id):
        """ hàm bắt sự kiện và xử lý khi khách hàng điền form đặt hàng và gửi"""
        product = Product.objects.get(pk = product_id) # lấy đối tượng sản phẩm được đặt
        orderform = OrderForm(request.POST) # lấy đối tượng form theo phản hồi từ người dùng trả về
        order = Order() # tạo đối tượng đơn đặt hàng để lưu về database
        if orderform.is_valid(): # nếu form trả về đúng định dạng
            order.name_product = product.name # lấy tên sản phẩm được đặt
            order.name_user = request.POST["name_user"] # lấy tên người đặt
            order.address = request.POST["address"] # lấy địa chỉ người đặt
            order.phone_number = request.POST["phone_number"] # lấy số điện thoại người đặt
            order.count = request.POST["count"] # lấy số lượng sản phẩm được đặt
            if(int(order.count) <= 0): return HttpResponse("vui lòng nhập số lượng lớn hơn 0") 
            # xử lý khi người đặt nhập số hàng nhỏ hơn 0
            order.value = int(request.POST["count"])*product.value # tính số tiền mà người đặt cần trả
            order.save() # lưu đơn hàng vào database
            return render(request,"product/view_pay.html",{"order":order}) 
            # trả về trang hiển thị đặt hàng thành công
        else: 
            return HttpResponse("bạn nhập sai định dạng") 
            # nếu không đúng định dạng thì truyền thông báo đến người dùng 
class Search(View):
    """ class xử lý tìm kiếm """
    def get(self,request): 
        """ hàm hiển thị trang tìm kiếm"""
        return render(request,"product/search.html")
    def post(self,request): 
        """hàm xử lý tìm kiếm"""
        search = request.POST['search'] # lấy phản hồi của người dùng từ search bar
        pros = Product.objects.filter(name__contains=search) # lấy danh sách sản phẩm được lọc ra từ database
        return render(request,"product/search.html",{"search":search,"pros":pros})
        # trả lại danh sách sản phẩm tìm được
def view_type(request,type_id):
    pro_type = Product_type.objects.get(pk= type_id) # lấy loại sản phẩm theo id của sản phẩm được chọn
    pros = pro_type.product_set.all() # lấy danh sách sản phầm thuộc loại sản phẩm đó
    return render(request,"product/view_type.html",{"pro_type":pro_type,"pros":pros})
    # trả về trang hiển thị danh sách sản phẩm thuộc loại sản phẩm đó 

store/product/templates/product/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>search</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <style>
          .height {
    height: 100vh
}

.search {
    position: relative;
    box-shadow: 0 0 40px rgba(51, 51, 51, .1)
}

.search input {
    height: 60px;
    text-indent: 25px;
    border: 2px solid #d6d4d4
}

.search input:focus {
    box-shadow: none;
    border: 2px solid blue
}

.search .fa-search {
    position: absolute;
    top: 20px;
    left: 16px
}

.search button {
    position: absolute;
    top: 5px;
    right: 5px;
    height: 50px;
    width: 110px;
    background: blue
}
        </style>
      </style>
      <!-- bootstrap css -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
      <link rel="stylesheet" href="{% static 'product/css/bootstrap.min.css'%}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'product/css/style.css'%}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'product/css/responsive.css'%}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'product/images/fevicon.png'%}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'product/css/jquery.mCustomScrollbar.min.css'%}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
      <!-- owl stylesheets --> 
      <link rel="stylesheet" href="{% static 'product/css/owl.carousel.min.css'%}">
      <link rel="stylesheet" href="{% static 'product/css/owl.theme.default.min.css'%}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout product_pagr">
      <!-- loader  -->
      </div>
      <!-- end loader -->
      <!-- header -->
      <header class="section" >
         <!-- header inner -->
        <div class="header_main" style="background-color:cornflowerblue;">
         <div class="header_main"style="background-color:cornflowerblue;">
            <div class="container">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo"> <a href="index.html"><img src="{% static 'product/images/logo.png'%}" alt="#"></a> </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9" >
                     <div class="menu-area">
                        <div class="limit-box">
                           <nav class="main-menu">
                              <ul class="menu-area-main">
                                 <li> <a href="{% url 'product:home'%}">Home</a> </li>
                                 <li> <a href="about.html">About</a> </li>
                                 <li><a href="testmonial.html">Testmonial</a></li>
                                 <li><a href="clients.html">Shop</a></li>
                                 <li><a href="contact.html">Contact Us</a></li>
                                 <li class="last"><a href="{% url 'product:search' %}"><img src="{% static 'product/images/search_icon.png'%}" alt="icon"/></a></li>
                              </ul>
                           </nav>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
        </div>
         <!-- end header inner -->
      </header>
      <!-- end header -->
      </header>
      <!-- end header -->
       <!-- plant -->
       <!-- thanh search bar để người dùng tìm kiếm -->
       <form action="{% url 'product:search' %}" method="post">
           {% csrf_token %}
        <div class="container">
            <div class="row height d-flex justify-content-center align-items-center">
                <div class="col-md-8">
                    <div class="search"> <i class="fa fa-search"></i> <input type="text" class="form-control" name="search"> 
                        <button class="btn btn-primary">Search</button> </div>
                </div>
            </div>
        </div>
    </form>

    <div class="clothes_main section " style="font-family: 'Times New Roman', Times, serif;">
        <div class="container">
          <div class="row">
             {% if search %}
             {% for pro in pros %}
             <!-- nếu người dùng có nhập vào thanh search bar và tìm thấy kết quả thì
              sẽ in ra danh sách sản phẩm tìm được -->
             <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12" >
                <div class="sport_product" style="width: 350px; height: 570px;" >
                  <a href="{% url 'product:view_product' pro.id %}"> <figure>
                     <img src="{{ pro.img_avata.url }}" alt="img" />
                  <h3><strong class="price_text">{{pro.value}} vnđ</strong></h3>
                   <h4>{{pro.name}}</h4></figure></a>
                   {{pro.description}}
                </div>
             </div>
             {% endfor %}
             {% else %}
             <!-- nếu không thì sẽ thông báo cho người dùng -->
             <h1>bạn chưa nhập gì</h1>
             {% endif %}
           </div>
          </div>
         </div>
    </div>

      <div id="plant" class="footer layout_padding">
         <div class="container">
            <p>© 2019 All Rights Reserved. Design by<a href="https://html.design/"> Free Html Templates</a></p>
         </div>
      </div>
     </div>

      <!-- Javascript files-->
      <script src="{% static 'product/js/jquery.min.js'%}"></script>
      <script src="{% static 'product/js/popper.min.js'%}"></script>
      <script src="{% static 'product/js/bootstrap.bundle.min.js'%}"></script>
      <script src="{% static 'product/js/jquery-3.0.0.min.js'%}"></script>
      <script src="{% static 'product/js/plugin.js'%}"></script>
      <!-- sidebar -->
      <script src="{% static 'product/js/jquery.mCustomScrollbar.concat.min.js'%}"></script>
      <script src="{% static 'product/js/custom.js'%}"></script>
      <!-- javascript --> 
      <script src="{% static 'product/js/owl.carousel.js'%}"></script>
      <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
      <script>
         $(document).ready(function(){
         $(".fancybox").fancybox({
         openEffect: "none",
         closeEffect: "none"
         });
         
         $(".zoom").hover(function(){
         
         $(this).addClass('transition');
         }, function(){
         
         $(this).removeClass('transition');
         });
         });
         
      </script> 


</body>
</html>

store/product/templates/product/view_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>{{pro.name}}</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'product/css/bootstrap.min.css'%}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'product/css/style.css'%}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'product/css/responsive.css'%}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'product/images/fevicon.png'%}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'product/css/jquery.mCustomScrollbar.min.css'%}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
      <!-- owl stylesheets --> 
      <link rel="stylesheet" href="{% static 'product/css/owl.carousel.min.css'%}">
      <link rel="stylesheet" href="{% static 'product/css/owl.theme.default.min.css'%}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout product_pagr">
      <!-- loader  -->
      </div>
      <!-- end loader -->
      <!-- header -->
      <header class="section">
         <!-- header inner -->
        <div class="header_main" style="background-color:cornflowerblue;">
         <div class="header_main"style="background-color:cornflowerblue;">
            <div class="container">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo"> <a href="index.html"><img src="{% static 'product/images/logo.png'%}" alt="#"></a> </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9" >
                     <div class="menu-area">
                        <div class="limit-box">
                           <nav class="main-menu">
                              <ul class="menu-area-main">
                                 <li> <a href="{% url 'product:home'%}">Home</a> </li>
                                 <li> <a href="about.html">About</a> </li>
                                 <li><a href="testmonial.html">Testmonial</a></li>
                                 <li><a href="clients.html">Shop</a></li>
                                 <li><a href="contact.html">Contact Us</a></li>
                                 <li class="last"><a href="{% url 'product:search' %}"><img src="{% static 'product/images/search_icon.png'%}" alt="icon"/></a></li>
                              </ul>
                           </nav>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
        </div>
         <!-- end header inner -->
      </header>
      <!-- end header -->
      </header>
      <!-- end header -->
       <!-- plant -->
      <div id="plant" class="section  product" style="font-family: 'Times New Roman', Times, serif;" >
         <div class="container">
            <div class="row">
               <div class="col-md-12 ">
                  <div class="titlepage">
                     <!-- in ra tên,giá,mô tả sản phẩm,chi tiết về sản phẩm -->
                     <h2><strong class="black">{{pro.name}}</strong></h2>
                     <strong style="color: red; font-size: 20px;">{{pro.value}} vnđ</strong>
                     <span>{{pro.description}}</span>
                     <p>{{pro.detail}}</p>
                  </div>
               </div>
            </div>
         </div>
      </div>
      
         <div class="clothes_main section ">
          <div class="container">
            <div class="row">
               {% for img in pro.picture_set.all %}
               <!-- lặp trong danh sách ảnh của sản phẩm và in ra -->
               <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12">
                  <div class="sport_product" style="width: 370px; height: 400px;" >
                     <figure><img src="{{ img.picture.url }}" alt="img"/></figure>
                     </div>
                  </div>
                  {% endfor %}
               </div>
         </div>
      </div>
     
      <!-- end plant -->
     <!-- footer start-->
     <div class="col-md-6" style="font-family: 'Times New Roman', Times, serif;">
     <div class="email_btn">
        <!-- in ra form đặt hàng để người dùng điền vào -->
      <form action="{% url 'product:view_product' pro.id %}" method="post"">
         {% csrf_token %}
         <strong style="font-size: 25px;"> Tên sản phẩm: {{pro.name}}</strong>
          <p style="color: red;">Giá:  {{pro.value}} vnđ</p>
         <p class="form-group"> Tên người nhận {{ f.name_user}}</p>
         <p class="form-group"> Địa chỉ người nhận {{ f.address}}</p>
         <p class="form-group"> Số điện thoại người nhận {{ f.phone_number}}</p>
         <p class="form-group" > Số lượng  {{ f.count}}</p>

         <div class="submit_btn">
            <button type="submit" class="btn btn-primary" style="background: #081b30; color: #fff; padding: 11px;">Đặt hàng</button>
         </div>
      </form>
     </div>
     </div>
      <div id="plant" class="footer layout_padding">
         <div class="container">
            <p>© 2019 All Rights Reserved. Design by<a href="https://html.design/"> Free Html Templates</a></p>
         </div>
      </div>
     </div>

      <!-- Javascript files-->
      <script src="{% static 'product/js/jquery.min.js'%}"></script>
      <script src="{% static 'product/js/popper.min.js'%}"></script>
      <script src="{% static 'product/js/bootstrap.bundle.min.js'%}"></script>
      <script src="{% static 'product/js/jquery-3.0.0.min.js'%}"></script>
      <script src="{% static 'product/js/plugin.js'%}"></script>
      <!-- sidebar -->
      <script src="{% static 'product/js/jquery.mCustomScrollbar.concat.min.js'%}"></script>
      <script src="{% static 'product/js/custom.js'%}"></script>
      <!-- javascript --> 
      <script src="{% static 'product/js/owl.carousel.js'%}"></script>
      <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
      <script>
         $(document).ready(function(){
         $(".fancybox").fancybox({
         openEffect: "none",
         closeEffect: "none"
         });
         
         $(".zoom").hover(function(){
         
         $(this).addClass('transition');
         }, function(){
         
         $(this).removeClass('transition');
         });
         });
         
      </script> 


</body>
</html>